### ISSUE TITLE
git hooks aren't being created & request for generator to support git repo initialization

### ISSUE THREAD

**Issue by calebcartwright** [swellaby/generator-swell#2]
@swellaby/core-collaborators - test
 
Currently, the generator automatically adds a git pre-commit hook via an npm library. However, as this library is being installed it checks for a git repo in the local directory. This will work fine provided that the user has done a git init or clone in the cwd prior to executing the generator, but otherwise a warning is displayed and the hook is not installed. 

As a short-term tactical solution we can display a notification to the user so that they know they need to run `npm i` after they have created a git repo. The strategic solution should provide optional support to create the git repo as part of the generation process

**Comment by beverts312** [comment]
@calebcartwright Since the generator makes what is, for most people, the root folder of there repo (or atleast the files/folders are structured that way), I think in most cases the user will not be generating the files in a location that is already a git repo  
I think that strategic solution makes a lot of sense

**Comment by calebcartwright** [comment]
@beverts312 agreed. moving it to the TODO column
